package com.android.nettylibrary.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

public final class MessageProtobuf {
  private MessageProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *��Ϣ����
     * </pre>
     *
     * <code>.ImMessage.TypeEnum type = 1;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     *��Ϣ����
     * </pre>
     *
     * <code>.ImMessage.TypeEnum type = 1;</code>
     */
    ImMessage.TypeEnum getType();

    /**
     * <pre>
     *��˾����
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    String getClientId();
    /**
     * <pre>
     *��˾����
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <pre>
     *������id
     * </pre>
     *
     * <code>string senderId = 3;</code>
     */
    String getSenderId();
    /**
     * <pre>
     *������id
     * </pre>
     *
     * <code>string senderId = 3;</code>
     */
    com.google.protobuf.ByteString
        getSenderIdBytes();

    /**
     * <pre>
     *������id
     * </pre>
     *
     * <code>string receiverId = 4;</code>
     */
    String getReceiverId();
    /**
     * <pre>
     *������id
     * </pre>
     *
     * <code>string receiverId = 4;</code>
     */
    com.google.protobuf.ByteString
        getReceiverIdBytes();

    /**
     * <pre>
     *Ⱥid
     * </pre>
     *
     * <code>string groupId = 5;</code>
     */
    String getGroupId();
    /**
     * <pre>
     *Ⱥid
     * </pre>
     *
     * <code>string groupId = 5;</code>
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <pre>
     *��Ϣָ��
     * </pre>
     *
     * <code>string fingerprint = 6;</code>
     */
    String getFingerprint();
    /**
     * <pre>
     *��Ϣָ��
     * </pre>
     *
     * <code>string fingerprint = 6;</code>
     */
    com.google.protobuf.ByteString
        getFingerprintBytes();

    /**
     * <pre>
     *��Ϣָ��
     * </pre>
     *
     * <code>repeated string fingerprints = 7;</code>
     */
    java.util.List<String>
        getFingerprintsList();
    /**
     * <pre>
     *��Ϣָ��
     * </pre>
     *
     * <code>repeated string fingerprints = 7;</code>
     */
    int getFingerprintsCount();
    /**
     * <pre>
     *��Ϣָ��
     * </pre>
     *
     * <code>repeated string fingerprints = 7;</code>
     */
    String getFingerprints(int index);
    /**
     * <pre>
     *��Ϣָ��
     * </pre>
     *
     * <code>repeated string fingerprints = 7;</code>
     */
    com.google.protobuf.ByteString
        getFingerprintsBytes(int index);

    /**
     * <pre>
     *����
     * </pre>
     *
     * <code>string data = 8;</code>
     */
    String getData();
    /**
     * <pre>
     *����
     * </pre>
     *
     * <code>string data = 8;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <pre>
     *�����ʱ���
     * </pre>
     *
     * <code>uint64 timestamp = 9;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     *�û�״̬
     * </pre>
     *
     * <code>.ImMessage.UserStatusEnum userStatus = 10;</code>
     */
    int getUserStatusValue();
    /**
     * <pre>
     *�û�״̬
     * </pre>
     *
     * <code>.ImMessage.UserStatusEnum userStatus = 10;</code>
     */
    ImMessage.UserStatusEnum getUserStatus();

    /**
     * <pre>
     *�豸id
     * </pre>
     *
     * <code>string deviceId = 11;</code>
     */
    String getDeviceId();
    /**
     * <pre>
     *�豸id
     * </pre>
     *
     * <code>string deviceId = 11;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <pre>
     *����״̬
     * </pre>
     *
     * <code>.ImMessage.ResponseStatusEnum responseStatus = 12;</code>
     */
    int getResponseStatusValue();
    /**
     * <pre>
     *����״̬
     * </pre>
     *
     * <code>.ImMessage.ResponseStatusEnum responseStatus = 12;</code>
     */
    ImMessage.ResponseStatusEnum getResponseStatus();

    /**
     * <pre>
     *�û���Ϣ����
     * </pre>
     *
     * <code>uint32 msgType = 13;</code>
     */
    int getMsgType();

    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string token = 14;</code>
     */
    String getToken();
    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string token = 14;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <pre>
     * �豸����
     * </pre>
     *
     * <code>.ImMessage.DeviceTypeEnum deviceType = 15;</code>
     */
    int getDeviceTypeValue();
    /**
     * <pre>
     * �豸����
     * </pre>
     *
     * <code>.ImMessage.DeviceTypeEnum deviceType = 15;</code>
     */
    ImMessage.DeviceTypeEnum getDeviceType();
  }
  /**
   * <pre>
   *������Ϣ
   * </pre>
   *
   * Protobuf type {@code ImMessage}
   */
  public  static final class ImMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImMessage)
      ImMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImMessage.newBuilder() to construct.
    private ImMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImMessage() {
      type_ = 0;
      clientId_ = "";
      senderId_ = "";
      receiverId_ = "";
      groupId_ = "";
      fingerprint_ = "";
      fingerprints_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      data_ = "";
      timestamp_ = 0L;
      userStatus_ = 0;
      deviceId_ = "";
      responseStatus_ = 0;
      msgType_ = 0;
      token_ = "";
      deviceType_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              senderId_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              receiverId_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              groupId_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              fingerprint_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                fingerprints_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              fingerprints_.add(s);
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 72: {

              timestamp_ = input.readUInt64();
              break;
            }
            case 80: {
              int rawValue = input.readEnum();

              userStatus_ = rawValue;
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 96: {
              int rawValue = input.readEnum();

              responseStatus_ = rawValue;
              break;
            }
            case 104: {

              msgType_ = input.readUInt32();
              break;
            }
            case 114: {
              String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 120: {
              int rawValue = input.readEnum();

              deviceType_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          fingerprints_ = fingerprints_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProtobuf.internal_static_ImMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProtobuf.internal_static_ImMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ImMessage.class, Builder.class);
    }

    /**
     * Protobuf enum {@code ImMessage.TypeEnum}
     */
    public enum TypeEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *��������
       * </pre>
       *
       * <code>HEARTBEAT = 0;</code>
       */
      HEARTBEAT(0),
      /**
       * <pre>
       *����ע�ᷢ������Ϣ��channel
       * </pre>
       *
       * <code>INFORMATION = 1;</code>
       */
      INFORMATION(1),
      /**
       * <pre>
       *�û���Ϣ
       * </pre>
       *
       * <code>USERMSG = 2;</code>
       */
      USERMSG(2),
      /**
       * <pre>
       *�ͻ�����Ϣ��ִ
       * </pre>
       *
       * <code>RECEIPT = 3;</code>
       */
      RECEIPT(3),
      /**
       * <pre>
       *�ͻ���λ��
       * </pre>
       *
       * <code>POSITION = 4;</code>
       */
      POSITION(4),
      /**
       * <pre>
       *�������Ϣ��ִ
       * </pre>
       *
       * <code>SERVERRECEIPT = 5;</code>
       */
      SERVERRECEIPT(5),
      /**
       * <pre>
       *�����ack��Ϣ��ִ �ͻ���ȷ���յ���Ϣ
       * </pre>
       *
       * <code>ACK = 6;</code>
       */
      ACK(6),
      /**
       * <pre>
       *Ⱥ������Ϣ
       * </pre>
       *
       * <code>KICKOUT = 7;</code>
       */
      KICKOUT(7),
      /**
       * <pre>
       *Ⱥ����
       * </pre>
       *
       * <code>PROHIBITIONS = 8;</code>
       */
      PROHIBITIONS(8),
      /**
       * <pre>
       *ϵͳ��Ϣ
       * </pre>
       *
       * <code>SYSTEM = 9;</code>
       */
      SYSTEM(9),
      /**
       * <pre>
       *�û�״̬��Ϣ
       * </pre>
       *
       * <code>USERSTATUS = 10;</code>
       */
      USERSTATUS(10),
      /**
       * <pre>
       *��Ϣ�Ѷ�ȷ��
       * </pre>
       *
       * <code>READ = 11;</code>
       */
      READ(11),
      /**
       * <pre>
       *token�����Ϣ
       * </pre>
       *
       * <code>TOKEN = 12;</code>
       */
      TOKEN(12),
      /**
       * <pre>
       *ɾ����Ϣ
       * </pre>
       *
       * <code>DELETE = 13;</code>
       */
      DELETE(13),
      /**
       * <pre>
       *������Ϣ�����¼�
       * </pre>
       *
       * <code>OFFLINEEVN = 14;</code>
       */
      OFFLINEEVN(14),
      /**
       * <pre>
       *������Ϣ
       * </pre>
       *
       * <code>SHIELD = 15;</code>
       */
      SHIELD(15),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *��������
       * </pre>
       *
       * <code>HEARTBEAT = 0;</code>
       */
      public static final int HEARTBEAT_VALUE = 0;
      /**
       * <pre>
       *����ע�ᷢ������Ϣ��channel
       * </pre>
       *
       * <code>INFORMATION = 1;</code>
       */
      public static final int INFORMATION_VALUE = 1;
      /**
       * <pre>
       *�û���Ϣ
       * </pre>
       *
       * <code>USERMSG = 2;</code>
       */
      public static final int USERMSG_VALUE = 2;
      /**
       * <pre>
       *�ͻ�����Ϣ��ִ
       * </pre>
       *
       * <code>RECEIPT = 3;</code>
       */
      public static final int RECEIPT_VALUE = 3;
      /**
       * <pre>
       *�ͻ���λ��
       * </pre>
       *
       * <code>POSITION = 4;</code>
       */
      public static final int POSITION_VALUE = 4;
      /**
       * <pre>
       *�������Ϣ��ִ
       * </pre>
       *
       * <code>SERVERRECEIPT = 5;</code>
       */
      public static final int SERVERRECEIPT_VALUE = 5;
      /**
       * <pre>
       *�����ack��Ϣ��ִ �ͻ���ȷ���յ���Ϣ
       * </pre>
       *
       * <code>ACK = 6;</code>
       */
      public static final int ACK_VALUE = 6;
      /**
       * <pre>
       *Ⱥ������Ϣ
       * </pre>
       *
       * <code>KICKOUT = 7;</code>
       */
      public static final int KICKOUT_VALUE = 7;
      /**
       * <pre>
       *Ⱥ����
       * </pre>
       *
       * <code>PROHIBITIONS = 8;</code>
       */
      public static final int PROHIBITIONS_VALUE = 8;
      /**
       * <pre>
       *ϵͳ��Ϣ
       * </pre>
       *
       * <code>SYSTEM = 9;</code>
       */
      public static final int SYSTEM_VALUE = 9;
      /**
       * <pre>
       *�û�״̬��Ϣ
       * </pre>
       *
       * <code>USERSTATUS = 10;</code>
       */
      public static final int USERSTATUS_VALUE = 10;
      /**
       * <pre>
       *��Ϣ�Ѷ�ȷ��
       * </pre>
       *
       * <code>READ = 11;</code>
       */
      public static final int READ_VALUE = 11;
      /**
       * <pre>
       *token�����Ϣ
       * </pre>
       *
       * <code>TOKEN = 12;</code>
       */
      public static final int TOKEN_VALUE = 12;
      /**
       * <pre>
       *ɾ����Ϣ
       * </pre>
       *
       * <code>DELETE = 13;</code>
       */
      public static final int DELETE_VALUE = 13;
      /**
       * <pre>
       *������Ϣ�����¼�
       * </pre>
       *
       * <code>OFFLINEEVN = 14;</code>
       */
      public static final int OFFLINEEVN_VALUE = 14;
      /**
       * <pre>
       *������Ϣ
       * </pre>
       *
       * <code>SHIELD = 15;</code>
       */
      public static final int SHIELD_VALUE = 15;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static TypeEnum valueOf(int value) {
        return forNumber(value);
      }

      public static TypeEnum forNumber(int value) {
        switch (value) {
          case 0: return HEARTBEAT;
          case 1: return INFORMATION;
          case 2: return USERMSG;
          case 3: return RECEIPT;
          case 4: return POSITION;
          case 5: return SERVERRECEIPT;
          case 6: return ACK;
          case 7: return KICKOUT;
          case 8: return PROHIBITIONS;
          case 9: return SYSTEM;
          case 10: return USERSTATUS;
          case 11: return READ;
          case 12: return TOKEN;
          case 13: return DELETE;
          case 14: return OFFLINEEVN;
          case 15: return SHIELD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TypeEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          TypeEnum> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TypeEnum>() {
              public TypeEnum findValueByNumber(int number) {
                return TypeEnum.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ImMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final TypeEnum[] VALUES = values();

      public static TypeEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private TypeEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ImMessage.TypeEnum)
    }

    /**
     * Protobuf enum {@code ImMessage.UserStatusEnum}
     */
    public enum UserStatusEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>OFFLINE = 0;</code>
       */
      OFFLINE(0),
      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>ONLINE = 1;</code>
       */
      ONLINE(1),
      /**
       * <pre>
       *æµ
       * </pre>
       *
       * <code>BUSY = 2;</code>
       */
      BUSY(2),
      /**
       * <pre>
       *�������豸��¼
       * </pre>
       *
       * <code>SQUEEZEOUT = 3;</code>
       */
      SQUEEZEOUT(3),
      /**
       * <pre>
       *�û���Ϣ�ı�
       * </pre>
       *
       * <code>CHANGE = 4;</code>
       */
      CHANGE(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>OFFLINE = 0;</code>
       */
      public static final int OFFLINE_VALUE = 0;
      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>ONLINE = 1;</code>
       */
      public static final int ONLINE_VALUE = 1;
      /**
       * <pre>
       *æµ
       * </pre>
       *
       * <code>BUSY = 2;</code>
       */
      public static final int BUSY_VALUE = 2;
      /**
       * <pre>
       *�������豸��¼
       * </pre>
       *
       * <code>SQUEEZEOUT = 3;</code>
       */
      public static final int SQUEEZEOUT_VALUE = 3;
      /**
       * <pre>
       *�û���Ϣ�ı�
       * </pre>
       *
       * <code>CHANGE = 4;</code>
       */
      public static final int CHANGE_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static UserStatusEnum valueOf(int value) {
        return forNumber(value);
      }

      public static UserStatusEnum forNumber(int value) {
        switch (value) {
          case 0: return OFFLINE;
          case 1: return ONLINE;
          case 2: return BUSY;
          case 3: return SQUEEZEOUT;
          case 4: return CHANGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<UserStatusEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          UserStatusEnum> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<UserStatusEnum>() {
              public UserStatusEnum findValueByNumber(int number) {
                return UserStatusEnum.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ImMessage.getDescriptor().getEnumTypes().get(1);
      }

      private static final UserStatusEnum[] VALUES = values();

      public static UserStatusEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private UserStatusEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ImMessage.UserStatusEnum)
    }

    /**
     * Protobuf enum {@code ImMessage.ResponseStatusEnum}
     */
    public enum ResponseStatusEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *�ɹ�
       * </pre>
       *
       * <code>SUCCESS = 0;</code>
       */
      SUCCESS(0),
      /**
       * <pre>
       *ʧ��
       * </pre>
       *
       * <code>FAIL = 1;</code>
       */
      FAIL(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *�ɹ�
       * </pre>
       *
       * <code>SUCCESS = 0;</code>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <pre>
       *ʧ��
       * </pre>
       *
       * <code>FAIL = 1;</code>
       */
      public static final int FAIL_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static ResponseStatusEnum valueOf(int value) {
        return forNumber(value);
      }

      public static ResponseStatusEnum forNumber(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return FAIL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResponseStatusEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ResponseStatusEnum> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResponseStatusEnum>() {
              public ResponseStatusEnum findValueByNumber(int number) {
                return ResponseStatusEnum.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ImMessage.getDescriptor().getEnumTypes().get(2);
      }

      private static final ResponseStatusEnum[] VALUES = values();

      public static ResponseStatusEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ResponseStatusEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ImMessage.ResponseStatusEnum)
    }

    /**
     * Protobuf enum {@code ImMessage.DeviceTypeEnum}
     */
    public enum DeviceTypeEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *PC��
       * </pre>
       *
       * <code>PC = 0;</code>
       */
      PC(0),
      /**
       * <pre>
       *IOS��
       * </pre>
       *
       * <code>IOS = 1;</code>
       */
      IOS(1),
      /**
       * <pre>
       *��׿
       * </pre>
       *
       * <code>Android = 2;</code>
       */
      Android(2),
      /**
       * <pre>
       *H5��
       * </pre>
       *
       * <code>WAP = 3;</code>
       */
      WAP(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *PC��
       * </pre>
       *
       * <code>PC = 0;</code>
       */
      public static final int PC_VALUE = 0;
      /**
       * <pre>
       *IOS��
       * </pre>
       *
       * <code>IOS = 1;</code>
       */
      public static final int IOS_VALUE = 1;
      /**
       * <pre>
       *��׿
       * </pre>
       *
       * <code>Android = 2;</code>
       */
      public static final int Android_VALUE = 2;
      /**
       * <pre>
       *H5��
       * </pre>
       *
       * <code>WAP = 3;</code>
       */
      public static final int WAP_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DeviceTypeEnum valueOf(int value) {
        return forNumber(value);
      }

      public static DeviceTypeEnum forNumber(int value) {
        switch (value) {
          case 0: return PC;
          case 1: return IOS;
          case 2: return Android;
          case 3: return WAP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DeviceTypeEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DeviceTypeEnum> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DeviceTypeEnum>() {
              public DeviceTypeEnum findValueByNumber(int number) {
                return DeviceTypeEnum.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ImMessage.getDescriptor().getEnumTypes().get(3);
      }

      private static final DeviceTypeEnum[] VALUES = values();

      public static DeviceTypeEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DeviceTypeEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ImMessage.DeviceTypeEnum)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     *��Ϣ����
     * </pre>
     *
     * <code>.ImMessage.TypeEnum type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *��Ϣ����
     * </pre>
     *
     * <code>.ImMessage.TypeEnum type = 1;</code>
     */
    public TypeEnum getType() {
      TypeEnum result = TypeEnum.valueOf(type_);
      return result == null ? TypeEnum.UNRECOGNIZED : result;
    }

    public static final int CLIENTID_FIELD_NUMBER = 2;
    private volatile Object clientId_;
    /**
     * <pre>
     *��˾����
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public String getClientId() {
      Object ref = clientId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *��˾����
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERID_FIELD_NUMBER = 3;
    private volatile Object senderId_;
    /**
     * <pre>
     *������id
     * </pre>
     *
     * <code>string senderId = 3;</code>
     */
    public String getSenderId() {
      Object ref = senderId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        senderId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *������id
     * </pre>
     *
     * <code>string senderId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      Object ref = senderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERID_FIELD_NUMBER = 4;
    private volatile Object receiverId_;
    /**
     * <pre>
     *������id
     * </pre>
     *
     * <code>string receiverId = 4;</code>
     */
    public String getReceiverId() {
      Object ref = receiverId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        receiverId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *������id
     * </pre>
     *
     * <code>string receiverId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverIdBytes() {
      Object ref = receiverId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        receiverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPID_FIELD_NUMBER = 5;
    private volatile Object groupId_;
    /**
     * <pre>
     *Ⱥid
     * </pre>
     *
     * <code>string groupId = 5;</code>
     */
    public String getGroupId() {
      Object ref = groupId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *Ⱥid
     * </pre>
     *
     * <code>string groupId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      Object ref = groupId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FINGERPRINT_FIELD_NUMBER = 6;
    private volatile Object fingerprint_;
    /**
     * <pre>
     *��Ϣָ��
     * </pre>
     *
     * <code>string fingerprint = 6;</code>
     */
    public String getFingerprint() {
      Object ref = fingerprint_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fingerprint_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *��Ϣָ��
     * </pre>
     *
     * <code>string fingerprint = 6;</code>
     */
    public com.google.protobuf.ByteString
        getFingerprintBytes() {
      Object ref = fingerprint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fingerprint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FINGERPRINTS_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList fingerprints_;
    /**
     * <pre>
     *��Ϣָ��
     * </pre>
     *
     * <code>repeated string fingerprints = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFingerprintsList() {
      return fingerprints_;
    }
    /**
     * <pre>
     *��Ϣָ��
     * </pre>
     *
     * <code>repeated string fingerprints = 7;</code>
     */
    public int getFingerprintsCount() {
      return fingerprints_.size();
    }
    /**
     * <pre>
     *��Ϣָ��
     * </pre>
     *
     * <code>repeated string fingerprints = 7;</code>
     */
    public String getFingerprints(int index) {
      return fingerprints_.get(index);
    }
    /**
     * <pre>
     *��Ϣָ��
     * </pre>
     *
     * <code>repeated string fingerprints = 7;</code>
     */
    public com.google.protobuf.ByteString
        getFingerprintsBytes(int index) {
      return fingerprints_.getByteString(index);
    }

    public static final int DATA_FIELD_NUMBER = 8;
    private volatile Object data_;
    /**
     * <pre>
     *����
     * </pre>
     *
     * <code>string data = 8;</code>
     */
    public String getData() {
      Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *����
     * </pre>
     *
     * <code>string data = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 9;
    private long timestamp_;
    /**
     * <pre>
     *�����ʱ���
     * </pre>
     *
     * <code>uint64 timestamp = 9;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int USERSTATUS_FIELD_NUMBER = 10;
    private int userStatus_;
    /**
     * <pre>
     *�û�״̬
     * </pre>
     *
     * <code>.ImMessage.UserStatusEnum userStatus = 10;</code>
     */
    public int getUserStatusValue() {
      return userStatus_;
    }
    /**
     * <pre>
     *�û�״̬
     * </pre>
     *
     * <code>.ImMessage.UserStatusEnum userStatus = 10;</code>
     */
    public UserStatusEnum getUserStatus() {
      UserStatusEnum result = UserStatusEnum.valueOf(userStatus_);
      return result == null ? UserStatusEnum.UNRECOGNIZED : result;
    }

    public static final int DEVICEID_FIELD_NUMBER = 11;
    private volatile Object deviceId_;
    /**
     * <pre>
     *�豸id
     * </pre>
     *
     * <code>string deviceId = 11;</code>
     */
    public String getDeviceId() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *�豸id
     * </pre>
     *
     * <code>string deviceId = 11;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSESTATUS_FIELD_NUMBER = 12;
    private int responseStatus_;
    /**
     * <pre>
     *����״̬
     * </pre>
     *
     * <code>.ImMessage.ResponseStatusEnum responseStatus = 12;</code>
     */
    public int getResponseStatusValue() {
      return responseStatus_;
    }
    /**
     * <pre>
     *����״̬
     * </pre>
     *
     * <code>.ImMessage.ResponseStatusEnum responseStatus = 12;</code>
     */
    public ResponseStatusEnum getResponseStatus() {
      ResponseStatusEnum result = ResponseStatusEnum.valueOf(responseStatus_);
      return result == null ? ResponseStatusEnum.UNRECOGNIZED : result;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 13;
    private int msgType_;
    /**
     * <pre>
     *�û���Ϣ����
     * </pre>
     *
     * <code>uint32 msgType = 13;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int TOKEN_FIELD_NUMBER = 14;
    private volatile Object token_;
    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string token = 14;</code>
     */
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string token = 14;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICETYPE_FIELD_NUMBER = 15;
    private int deviceType_;
    /**
     * <pre>
     * �豸����
     * </pre>
     *
     * <code>.ImMessage.DeviceTypeEnum deviceType = 15;</code>
     */
    public int getDeviceTypeValue() {
      return deviceType_;
    }
    /**
     * <pre>
     * �豸����
     * </pre>
     *
     * <code>.ImMessage.DeviceTypeEnum deviceType = 15;</code>
     */
    public DeviceTypeEnum getDeviceType() {
      DeviceTypeEnum result = DeviceTypeEnum.valueOf(deviceType_);
      return result == null ? DeviceTypeEnum.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != TypeEnum.HEARTBEAT.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientId_);
      }
      if (!getSenderIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, senderId_);
      }
      if (!getReceiverIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, receiverId_);
      }
      if (!getGroupIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, groupId_);
      }
      if (!getFingerprintBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, fingerprint_);
      }
      for (int i = 0; i < fingerprints_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, fingerprints_.getRaw(i));
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, data_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(9, timestamp_);
      }
      if (userStatus_ != UserStatusEnum.OFFLINE.getNumber()) {
        output.writeEnum(10, userStatus_);
      }
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, deviceId_);
      }
      if (responseStatus_ != ResponseStatusEnum.SUCCESS.getNumber()) {
        output.writeEnum(12, responseStatus_);
      }
      if (msgType_ != 0) {
        output.writeUInt32(13, msgType_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, token_);
      }
      if (deviceType_ != DeviceTypeEnum.PC.getNumber()) {
        output.writeEnum(15, deviceType_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != TypeEnum.HEARTBEAT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientId_);
      }
      if (!getSenderIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, senderId_);
      }
      if (!getReceiverIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, receiverId_);
      }
      if (!getGroupIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, groupId_);
      }
      if (!getFingerprintBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, fingerprint_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fingerprints_.size(); i++) {
          dataSize += computeStringSizeNoTag(fingerprints_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFingerprintsList().size();
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, data_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(9, timestamp_);
      }
      if (userStatus_ != UserStatusEnum.OFFLINE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, userStatus_);
      }
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, deviceId_);
      }
      if (responseStatus_ != ResponseStatusEnum.SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(12, responseStatus_);
      }
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(13, msgType_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, token_);
      }
      if (deviceType_ != DeviceTypeEnum.PC.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(15, deviceType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ImMessage)) {
        return super.equals(obj);
      }
      ImMessage other = (ImMessage) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getClientId()
          .equals(other.getClientId());
      result = result && getSenderId()
          .equals(other.getSenderId());
      result = result && getReceiverId()
          .equals(other.getReceiverId());
      result = result && getGroupId()
          .equals(other.getGroupId());
      result = result && getFingerprint()
          .equals(other.getFingerprint());
      result = result && getFingerprintsList()
          .equals(other.getFingerprintsList());
      result = result && getData()
          .equals(other.getData());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && userStatus_ == other.userStatus_;
      result = result && getDeviceId()
          .equals(other.getDeviceId());
      result = result && responseStatus_ == other.responseStatus_;
      result = result && (getMsgType()
          == other.getMsgType());
      result = result && getToken()
          .equals(other.getToken());
      result = result && deviceType_ == other.deviceType_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + SENDERID_FIELD_NUMBER;
      hash = (53 * hash) + getSenderId().hashCode();
      hash = (37 * hash) + RECEIVERID_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverId().hashCode();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId().hashCode();
      hash = (37 * hash) + FINGERPRINT_FIELD_NUMBER;
      hash = (53 * hash) + getFingerprint().hashCode();
      if (getFingerprintsCount() > 0) {
        hash = (37 * hash) + FINGERPRINTS_FIELD_NUMBER;
        hash = (53 * hash) + getFingerprintsList().hashCode();
      }
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + USERSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + userStatus_;
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + RESPONSESTATUS_FIELD_NUMBER;
      hash = (53 * hash) + responseStatus_;
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + DEVICETYPE_FIELD_NUMBER;
      hash = (53 * hash) + deviceType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ImMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ImMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ImMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *������Ϣ
     * </pre>
     *
     * Protobuf type {@code ImMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImMessage)
        ImMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageProtobuf.internal_static_ImMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageProtobuf.internal_static_ImMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ImMessage.class, Builder.class);
      }

      // Construct using MessageProtobuf.ImMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        clientId_ = "";

        senderId_ = "";

        receiverId_ = "";

        groupId_ = "";

        fingerprint_ = "";

        fingerprints_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        data_ = "";

        timestamp_ = 0L;

        userStatus_ = 0;

        deviceId_ = "";

        responseStatus_ = 0;

        msgType_ = 0;

        token_ = "";

        deviceType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProtobuf.internal_static_ImMessage_descriptor;
      }

      public ImMessage getDefaultInstanceForType() {
        return ImMessage.getDefaultInstance();
      }

      public ImMessage build() {
        ImMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ImMessage buildPartial() {
        ImMessage result = new ImMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        result.clientId_ = clientId_;
        result.senderId_ = senderId_;
        result.receiverId_ = receiverId_;
        result.groupId_ = groupId_;
        result.fingerprint_ = fingerprint_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          fingerprints_ = fingerprints_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.fingerprints_ = fingerprints_;
        result.data_ = data_;
        result.timestamp_ = timestamp_;
        result.userStatus_ = userStatus_;
        result.deviceId_ = deviceId_;
        result.responseStatus_ = responseStatus_;
        result.msgType_ = msgType_;
        result.token_ = token_;
        result.deviceType_ = deviceType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ImMessage) {
          return mergeFrom((ImMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ImMessage other) {
        if (other == ImMessage.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (!other.getSenderId().isEmpty()) {
          senderId_ = other.senderId_;
          onChanged();
        }
        if (!other.getReceiverId().isEmpty()) {
          receiverId_ = other.receiverId_;
          onChanged();
        }
        if (!other.getGroupId().isEmpty()) {
          groupId_ = other.groupId_;
          onChanged();
        }
        if (!other.getFingerprint().isEmpty()) {
          fingerprint_ = other.fingerprint_;
          onChanged();
        }
        if (!other.fingerprints_.isEmpty()) {
          if (fingerprints_.isEmpty()) {
            fingerprints_ = other.fingerprints_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureFingerprintsIsMutable();
            fingerprints_.addAll(other.fingerprints_);
          }
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.userStatus_ != 0) {
          setUserStatusValue(other.getUserStatusValue());
        }
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.responseStatus_ != 0) {
          setResponseStatusValue(other.getResponseStatusValue());
        }
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.deviceType_ != 0) {
          setDeviceTypeValue(other.getDeviceTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ImMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ImMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <pre>
       *��Ϣ����
       * </pre>
       *
       * <code>.ImMessage.TypeEnum type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       *��Ϣ����
       * </pre>
       *
       * <code>.ImMessage.TypeEnum type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣ����
       * </pre>
       *
       * <code>.ImMessage.TypeEnum type = 1;</code>
       */
      public TypeEnum getType() {
        TypeEnum result = TypeEnum.valueOf(type_);
        return result == null ? TypeEnum.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *��Ϣ����
       * </pre>
       *
       * <code>.ImMessage.TypeEnum type = 1;</code>
       */
      public Builder setType(TypeEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣ����
       * </pre>
       *
       * <code>.ImMessage.TypeEnum type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private Object clientId_ = "";
      /**
       * <pre>
       *��˾����
       * </pre>
       *
       * <code>string clientId = 2;</code>
       */
      public String getClientId() {
        Object ref = clientId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *��˾����
       * </pre>
       *
       * <code>string clientId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *��˾����
       * </pre>
       *
       * <code>string clientId = 2;</code>
       */
      public Builder setClientId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��˾����
       * </pre>
       *
       * <code>string clientId = 2;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��˾����
       * </pre>
       *
       * <code>string clientId = 2;</code>
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private Object senderId_ = "";
      /**
       * <pre>
       *������id
       * </pre>
       *
       * <code>string senderId = 3;</code>
       */
      public String getSenderId() {
        Object ref = senderId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          senderId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *������id
       * </pre>
       *
       * <code>string senderId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSenderIdBytes() {
        Object ref = senderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          senderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *������id
       * </pre>
       *
       * <code>string senderId = 3;</code>
       */
      public Builder setSenderId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *������id
       * </pre>
       *
       * <code>string senderId = 3;</code>
       */
      public Builder clearSenderId() {
        
        senderId_ = getDefaultInstance().getSenderId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *������id
       * </pre>
       *
       * <code>string senderId = 3;</code>
       */
      public Builder setSenderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderId_ = value;
        onChanged();
        return this;
      }

      private Object receiverId_ = "";
      /**
       * <pre>
       *������id
       * </pre>
       *
       * <code>string receiverId = 4;</code>
       */
      public String getReceiverId() {
        Object ref = receiverId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          receiverId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *������id
       * </pre>
       *
       * <code>string receiverId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverIdBytes() {
        Object ref = receiverId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          receiverId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *������id
       * </pre>
       *
       * <code>string receiverId = 4;</code>
       */
      public Builder setReceiverId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *������id
       * </pre>
       *
       * <code>string receiverId = 4;</code>
       */
      public Builder clearReceiverId() {
        
        receiverId_ = getDefaultInstance().getReceiverId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *������id
       * </pre>
       *
       * <code>string receiverId = 4;</code>
       */
      public Builder setReceiverIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverId_ = value;
        onChanged();
        return this;
      }

      private Object groupId_ = "";
      /**
       * <pre>
       *Ⱥid
       * </pre>
       *
       * <code>string groupId = 5;</code>
       */
      public String getGroupId() {
        Object ref = groupId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *Ⱥid
       * </pre>
       *
       * <code>string groupId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *Ⱥid
       * </pre>
       *
       * <code>string groupId = 5;</code>
       */
      public Builder setGroupId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Ⱥid
       * </pre>
       *
       * <code>string groupId = 5;</code>
       */
      public Builder clearGroupId() {
        
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Ⱥid
       * </pre>
       *
       * <code>string groupId = 5;</code>
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupId_ = value;
        onChanged();
        return this;
      }

      private Object fingerprint_ = "";
      /**
       * <pre>
       *��Ϣָ��
       * </pre>
       *
       * <code>string fingerprint = 6;</code>
       */
      public String getFingerprint() {
        Object ref = fingerprint_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fingerprint_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *��Ϣָ��
       * </pre>
       *
       * <code>string fingerprint = 6;</code>
       */
      public com.google.protobuf.ByteString
          getFingerprintBytes() {
        Object ref = fingerprint_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fingerprint_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *��Ϣָ��
       * </pre>
       *
       * <code>string fingerprint = 6;</code>
       */
      public Builder setFingerprint(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fingerprint_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣָ��
       * </pre>
       *
       * <code>string fingerprint = 6;</code>
       */
      public Builder clearFingerprint() {
        
        fingerprint_ = getDefaultInstance().getFingerprint();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣָ��
       * </pre>
       *
       * <code>string fingerprint = 6;</code>
       */
      public Builder setFingerprintBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fingerprint_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList fingerprints_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFingerprintsIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          fingerprints_ = new com.google.protobuf.LazyStringArrayList(fingerprints_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <pre>
       *��Ϣָ��
       * </pre>
       *
       * <code>repeated string fingerprints = 7;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFingerprintsList() {
        return fingerprints_.getUnmodifiableView();
      }
      /**
       * <pre>
       *��Ϣָ��
       * </pre>
       *
       * <code>repeated string fingerprints = 7;</code>
       */
      public int getFingerprintsCount() {
        return fingerprints_.size();
      }
      /**
       * <pre>
       *��Ϣָ��
       * </pre>
       *
       * <code>repeated string fingerprints = 7;</code>
       */
      public String getFingerprints(int index) {
        return fingerprints_.get(index);
      }
      /**
       * <pre>
       *��Ϣָ��
       * </pre>
       *
       * <code>repeated string fingerprints = 7;</code>
       */
      public com.google.protobuf.ByteString
          getFingerprintsBytes(int index) {
        return fingerprints_.getByteString(index);
      }
      /**
       * <pre>
       *��Ϣָ��
       * </pre>
       *
       * <code>repeated string fingerprints = 7;</code>
       */
      public Builder setFingerprints(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFingerprintsIsMutable();
        fingerprints_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣָ��
       * </pre>
       *
       * <code>repeated string fingerprints = 7;</code>
       */
      public Builder addFingerprints(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFingerprintsIsMutable();
        fingerprints_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣָ��
       * </pre>
       *
       * <code>repeated string fingerprints = 7;</code>
       */
      public Builder addAllFingerprints(
          Iterable<String> values) {
        ensureFingerprintsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fingerprints_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣָ��
       * </pre>
       *
       * <code>repeated string fingerprints = 7;</code>
       */
      public Builder clearFingerprints() {
        fingerprints_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣָ��
       * </pre>
       *
       * <code>repeated string fingerprints = 7;</code>
       */
      public Builder addFingerprintsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureFingerprintsIsMutable();
        fingerprints_.add(value);
        onChanged();
        return this;
      }

      private Object data_ = "";
      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>string data = 8;</code>
       */
      public String getData() {
        Object ref = data_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>string data = 8;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>string data = 8;</code>
       */
      public Builder setData(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>string data = 8;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>string data = 8;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       *�����ʱ���
       * </pre>
       *
       * <code>uint64 timestamp = 9;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       *�����ʱ���
       * </pre>
       *
       * <code>uint64 timestamp = 9;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�����ʱ���
       * </pre>
       *
       * <code>uint64 timestamp = 9;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int userStatus_ = 0;
      /**
       * <pre>
       *�û�״̬
       * </pre>
       *
       * <code>.ImMessage.UserStatusEnum userStatus = 10;</code>
       */
      public int getUserStatusValue() {
        return userStatus_;
      }
      /**
       * <pre>
       *�û�״̬
       * </pre>
       *
       * <code>.ImMessage.UserStatusEnum userStatus = 10;</code>
       */
      public Builder setUserStatusValue(int value) {
        userStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�û�״̬
       * </pre>
       *
       * <code>.ImMessage.UserStatusEnum userStatus = 10;</code>
       */
      public UserStatusEnum getUserStatus() {
        UserStatusEnum result = UserStatusEnum.valueOf(userStatus_);
        return result == null ? UserStatusEnum.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *�û�״̬
       * </pre>
       *
       * <code>.ImMessage.UserStatusEnum userStatus = 10;</code>
       */
      public Builder setUserStatus(UserStatusEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        userStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�û�״̬
       * </pre>
       *
       * <code>.ImMessage.UserStatusEnum userStatus = 10;</code>
       */
      public Builder clearUserStatus() {
        
        userStatus_ = 0;
        onChanged();
        return this;
      }

      private Object deviceId_ = "";
      /**
       * <pre>
       *�豸id
       * </pre>
       *
       * <code>string deviceId = 11;</code>
       */
      public String getDeviceId() {
        Object ref = deviceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *�豸id
       * </pre>
       *
       * <code>string deviceId = 11;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *�豸id
       * </pre>
       *
       * <code>string deviceId = 11;</code>
       */
      public Builder setDeviceId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�豸id
       * </pre>
       *
       * <code>string deviceId = 11;</code>
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�豸id
       * </pre>
       *
       * <code>string deviceId = 11;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private int responseStatus_ = 0;
      /**
       * <pre>
       *����״̬
       * </pre>
       *
       * <code>.ImMessage.ResponseStatusEnum responseStatus = 12;</code>
       */
      public int getResponseStatusValue() {
        return responseStatus_;
      }
      /**
       * <pre>
       *����״̬
       * </pre>
       *
       * <code>.ImMessage.ResponseStatusEnum responseStatus = 12;</code>
       */
      public Builder setResponseStatusValue(int value) {
        responseStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *����״̬
       * </pre>
       *
       * <code>.ImMessage.ResponseStatusEnum responseStatus = 12;</code>
       */
      public ResponseStatusEnum getResponseStatus() {
        ResponseStatusEnum result = ResponseStatusEnum.valueOf(responseStatus_);
        return result == null ? ResponseStatusEnum.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *����״̬
       * </pre>
       *
       * <code>.ImMessage.ResponseStatusEnum responseStatus = 12;</code>
       */
      public Builder setResponseStatus(ResponseStatusEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        responseStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *����״̬
       * </pre>
       *
       * <code>.ImMessage.ResponseStatusEnum responseStatus = 12;</code>
       */
      public Builder clearResponseStatus() {
        
        responseStatus_ = 0;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <pre>
       *�û���Ϣ����
       * </pre>
       *
       * <code>uint32 msgType = 13;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <pre>
       *�û���Ϣ����
       * </pre>
       *
       * <code>uint32 msgType = 13;</code>
       */
      public Builder setMsgType(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�û���Ϣ����
       * </pre>
       *
       * <code>uint32 msgType = 13;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private Object token_ = "";
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 14;</code>
       */
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 14;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 14;</code>
       */
      public Builder setToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 14;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 14;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private int deviceType_ = 0;
      /**
       * <pre>
       * �豸����
       * </pre>
       *
       * <code>.ImMessage.DeviceTypeEnum deviceType = 15;</code>
       */
      public int getDeviceTypeValue() {
        return deviceType_;
      }
      /**
       * <pre>
       * �豸����
       * </pre>
       *
       * <code>.ImMessage.DeviceTypeEnum deviceType = 15;</code>
       */
      public Builder setDeviceTypeValue(int value) {
        deviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * �豸����
       * </pre>
       *
       * <code>.ImMessage.DeviceTypeEnum deviceType = 15;</code>
       */
      public DeviceTypeEnum getDeviceType() {
        DeviceTypeEnum result = DeviceTypeEnum.valueOf(deviceType_);
        return result == null ? DeviceTypeEnum.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * �豸����
       * </pre>
       *
       * <code>.ImMessage.DeviceTypeEnum deviceType = 15;</code>
       */
      public Builder setDeviceType(DeviceTypeEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        deviceType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * �豸����
       * </pre>
       *
       * <code>.ImMessage.DeviceTypeEnum deviceType = 15;</code>
       */
      public Builder clearDeviceType() {
        
        deviceType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImMessage)
    }

    // @@protoc_insertion_point(class_scope:ImMessage)
    private static final ImMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ImMessage();
    }

    public static ImMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImMessage>
        PARSER = new com.google.protobuf.AbstractParser<ImMessage>() {
      public ImMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ImMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ImMessage> getParserForType() {
      return PARSER;
    }

    public ImMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tmsg.proto\"\252\006\n\tImMessage\022!\n\004type\030\001 \001(\0162" +
      "\023.ImMessage.TypeEnum\022\020\n\010clientId\030\002 \001(\t\022\020" +
      "\n\010senderId\030\003 \001(\t\022\022\n\nreceiverId\030\004 \001(\t\022\017\n\007" +
      "groupId\030\005 \001(\t\022\023\n\013fingerprint\030\006 \001(\t\022\024\n\014fi" +
      "ngerprints\030\007 \003(\t\022\014\n\004data\030\010 \001(\t\022\021\n\ttimest" +
      "amp\030\t \001(\004\022-\n\nuserStatus\030\n \001(\0162\031.ImMessag" +
      "e.UserStatusEnum\022\020\n\010deviceId\030\013 \001(\t\0225\n\016re" +
      "sponseStatus\030\014 \001(\0162\035.ImMessage.ResponseS" +
      "tatusEnum\022\017\n\007msgType\030\r \001(\r\022\r\n\005token\030\016 \001(" +
      "\t\022-\n\ndeviceType\030\017 \001(\0162\031.ImMessage.Device",
      "TypeEnum\"\346\001\n\010TypeEnum\022\r\n\tHEARTBEAT\020\000\022\017\n\013" +
      "INFORMATION\020\001\022\013\n\007USERMSG\020\002\022\013\n\007RECEIPT\020\003\022" +
      "\014\n\010POSITION\020\004\022\021\n\rSERVERRECEIPT\020\005\022\007\n\003ACK\020" +
      "\006\022\013\n\007KICKOUT\020\007\022\020\n\014PROHIBITIONS\020\010\022\n\n\006SYST" +
      "EM\020\t\022\016\n\nUSERSTATUS\020\n\022\010\n\004READ\020\013\022\t\n\005TOKEN\020" +
      "\014\022\n\n\006DELETE\020\r\022\016\n\nOFFLINEEVN\020\016\022\n\n\006SHIELD\020" +
      "\017\"O\n\016UserStatusEnum\022\013\n\007OFFLINE\020\000\022\n\n\006ONLI" +
      "NE\020\001\022\010\n\004BUSY\020\002\022\016\n\nSQUEEZEOUT\020\003\022\n\n\006CHANGE" +
      "\020\004\"+\n\022ResponseStatusEnum\022\013\n\007SUCCESS\020\000\022\010\n" +
      "\004FAIL\020\001\"7\n\016DeviceTypeEnum\022\006\n\002PC\020\000\022\007\n\003IOS",
      "\020\001\022\013\n\007Android\020\002\022\007\n\003WAP\020\003B\021B\017MessageProto" +
      "bufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ImMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImMessage_descriptor,
        new String[] { "Type", "ClientId", "SenderId", "ReceiverId", "GroupId", "Fingerprint", "Fingerprints", "Data", "Timestamp", "UserStatus", "DeviceId", "ResponseStatus", "MsgType", "Token", "DeviceType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
